"""Compatibility re-exports for the pre-split Owl core module."""

from .agents import (
    AgentRef,
    GLOBAL_AGENT_NAME,
    list_states,
    load_state,
    make_ref,
    normalize_name,
    resolve_name,
    status_for_state,
    touch_state,
)
from .constants import (
    DEFAULT_WATCH_INTERVAL_SECONDS,
    EVENT_COMPACT,
    EVENT_MEMORY,
    EVENT_MESSAGE,
    EVENT_READ,
    ROLE_CC,
    ROLE_TO,
    SOURCE_BUILTIN,
    SOURCE_CUSTOM,
    STATUS_IDLE,
    STATUS_OFFLINE,
    STATUS_ONLINE,
    STATUS_UNKNOWN,
)
from .errors import OwlError, die
from .memory import (
    append_memory,
    effective_memory,
    memory_events,
    memory_scope_refs,
    visible_effective_memory,
    visible_memory_events,
)
from .messages import (
    MailboxWatcher,
    WatchRegistration,
    append_message_event,
    inbox_rows,
    message_events,
    notify_watchers,
    process_alive,
    read_message,
    send_message,
    sent_rows,
    summarize_messages,
    stop_process,
    unlink_if_exists,
    unread_count,
    watch_socket_path,
)
from .output import format_text_message, tsv_cell, write_json, write_tsv
from .spells import (
    all_spells,
    cast_spell,
    collect_spells_from_path,
    extract_description,
    filter_spells,
    load_builtin_spells,
    normalize_spell_path,
    spell_file_path,
)
from .store import Store, json_line, json_text, parse_jsonl_line
from .utils import parse_time, preview, utc_now

__all__ = [
    "AgentRef",
    "DEFAULT_WATCH_INTERVAL_SECONDS",
    "EVENT_COMPACT",
    "EVENT_MEMORY",
    "EVENT_MESSAGE",
    "EVENT_READ",
    "GLOBAL_AGENT_NAME",
    "MailboxWatcher",
    "OwlError",
    "ROLE_CC",
    "ROLE_TO",
    "SOURCE_BUILTIN",
    "SOURCE_CUSTOM",
    "STATUS_IDLE",
    "STATUS_OFFLINE",
    "STATUS_ONLINE",
    "STATUS_UNKNOWN",
    "Store",
    "WatchRegistration",
    "all_spells",
    "append_memory",
    "append_message_event",
    "cast_spell",
    "collect_spells_from_path",
    "die",
    "effective_memory",
    "extract_description",
    "filter_spells",
    "format_text_message",
    "inbox_rows",
    "json_line",
    "json_text",
    "list_states",
    "load_builtin_spells",
    "load_state",
    "make_ref",
    "memory_events",
    "memory_scope_refs",
    "message_events",
    "notify_watchers",
    "normalize_name",
    "normalize_spell_path",
    "parse_jsonl_line",
    "parse_time",
    "preview",
    "process_alive",
    "read_message",
    "resolve_name",
    "send_message",
    "sent_rows",
    "spell_file_path",
    "status_for_state",
    "stop_process",
    "summarize_messages",
    "touch_state",
    "tsv_cell",
    "unread_count",
    "unlink_if_exists",
    "utc_now",
    "visible_effective_memory",
    "visible_memory_events",
    "watch_socket_path",
    "write_json",
    "write_tsv",
]
